services:
  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: holaktal123
      MYSQL_DATABASE: beta-oto
      MYSQL_USER: daichi
      MYSQL_PASSWORD: holaktal123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
    context: ./backend
    container_name: php-apache
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mariadb

volumes:
  db_data:
